spring:
  application:
    name: school-service

#  datasource:
#    url: jdbc:mysql://www.jjjyyds.club:3306/volunteer?useUnicode=yes&characterEncoding=utf8
#    username: zhaojian
#    password: Zj1204??
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9002

eureka:
  client:
    service-url:
      -defaultZone: http://127.0.0.1:9000/eureka
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
