server:
  port: 80

eureka:
  client:
    service-url:
      -defaultZone: http://127.0.0.1:10000/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedHeaders: "*"
            allowedOrigins: "*" # 跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTION
      routes:
        - id: sys
          uri: lb://sys-service
          predicates:
            - Path=/sys/**
        - id: school
          uri: lb://school-service
          predicates:
            - Path=/school/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: file
          uri: lb://file-service
          predicates:
            - Path=/file/**
            - Path=/xml/**
        - id: task
          uri: lb://task-service
          predicates:
            - Path=/task/**