server:
  port: 9004
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://www.jjjyyds.club:3306/volunteer?useUnicode=yes&characterEncoding=utf8
    username: zhaojian
    password: Zj1204??
    driver-class-name: com.mysql.cj.jdbc.Driver






shiro:
  enabled: true
# 验证码开关
verify:
  enabled: true

hayek:
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认30天
    cookieTimeout: 2592000