server:
  port: 9004
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://www.jjjyyds.club:3306/volunteer?useUnicode=yes&characterEncoding=utf8
    username: zhaojian
    password: Zj1204??
    driver-class-name: com.mysql.cj.jdbc.Driver



# 验证码开关
verify:
  enabled: true
