
spring:
  application:
    name: sys-service



# mybatis 扫描路径配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    com:
      zj:
        sys:
          mapper: DEBUG





