spring:
  jmx:
    default-domain: sys-service
  application:
    name: sys-service
  # springboot 数据库配置
  datasource:
    url: jdbc:mysql://www.jjjyyds.club:3306/volunteer?useUnicode=yes&characterEncoding=utf8
    username: zhaojian
    password: Zj1204??
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 9009

# mybatis 扫描路径配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    com:
      zj:
        sys:
          mapper: DEBUG


volunteer:
  is-open-verify: false


