server:
  port: 9004
spring:
  application:
    name: auth-service


eureka:
  client:
    service-url:
      -defaultZone: http://127.0.0.1:9000/eureka



shiro:
  enabled: true
# 验证码开关
verify:
  enabled: true

hayek:
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认30天
    cookieTimeout: 2592000
redis:
  jedis:
    host: www.jjjyyds.club # reids端口
    password: 123123 # 密码